version: '3'
services:
  backend:
    container_name: backend
    image: julimax/app-backend:v0.0.9
    ports:
      - 3002:3002
    networks:
      - my_net

  frontend:
    container_name: frontend
    image: julimax/app-frontend:v0.0.15
    ports:
      - 80:3000
    networks:
      - my_net
    stdin_open: true
    tty: true

networks:
  my_net:
